FROM python:3.7

ARG DEVELOPER=

RUN apt update \
 && apt install -y --no-install-recommends libfaketime \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /cogs
ADD requirements.base.txt .

RUN pip install -U pip wheel setuptools \
 && pip install -r requirements.base.txt

ADD . .

EXPOSE 8000
VOLUME /cogs/config.yaml
VOLUME /uploads

ENV PYTHONDEVMODE $DEVELOPER
ENV LD_PRELOAD /usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
CMD ./start.sh
