FROM python:3.7

WORKDIR /cogs
ADD requirements.base.txt .

RUN pip install -U pip wheel setuptools \
 && pip install -r requirements.base.txt

ADD . .

EXPOSE 8000
VOLUME /cogs/config.yaml
VOLUME /uploads

CMD ./start.sh
