FROM python:3.7

WORKDIR /cogs
ADD requirements.base.txt requirements.auth.txt ./

RUN pip install -U pip wheel setuptools \
 && pip install -r requirements.base.txt \
                -r requirements.auth.txt

ADD . .

EXPOSE 8000
VOLUME /cogs/config.yaml
VOLUME /uploads

CMD ./start.sh -OO
