def double(value: float, digits: int = ...) -> str: ...
def number(value: float) -> str: ...
def ordinal(value: float) -> str: ...
def percentage(value: float, digits: int = ...) -> str: ...
def word(value: float, digits: int = ...) -> str: ...
